dist: xenial

language: go

env:
 - GO111MODULE=on

go:
 - 1.11.x
 - stable
 - tip


# Don't do `go get` for deps since the build/test phases take care
# of that when using modules.
install: true

before_script:
 - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.16.0

script:
 - golangci-lint run
 - go build
 - go test -v -race ./...
